#### general settings
name: diffFFFFFFFFFF
use_tb_logger: false
model: denoising
distortion: sr
gpu_ids: [2]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 1
  
#### datasets
datasets:
  train:
    optimizer: AdamW # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/zhku04/zhku04/mxs/CVPR25NTIRE多场景雨滴去除/EDiffSR-main/codes/config/sisr/AIDdataAfter/train/GT2
    dataroot_LQ: /home/zhku04/zhku04/mxs/CVPR25NTIRE多场景雨滴去除/EDiffSR-main/codes/config/sisr/AIDdataAfter/train/LR2

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 2
    GT_size: 64
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/zhku04/zhku04/mxs/CVPR25NTIRE多场景雨滴去除/EDiffSR-main/codes/config/sisr/AID-tiny/GT
    dataroot_LQ: /home/zhku04/zhku04/mxs/CVPR25NTIRE多场景雨滴去除/EDiffSR-main/codes/config/sisr/AID-tiny/LR
#/home/zhku04/zhku04/mxs/CVPR25NTIRE多场景雨滴去除/EDiffSR-main/codes/config/sisr/AID-tiny/GT
#### network structures
network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 64
    enc_blk_nums: [14, 1, 1, 1]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]

#### path
path:
#  pretrain_model_G: /home/zjh/zrl/experimentsunder/sisr/dif/models/500000_G.pth
  pretrain_model_G: ~
  strict_load: true
#  resume_state: /home/zjh/zrl/experiments/sisr/dif/training_state/15000.state
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: AdamW # Adam, AdamW, Lion
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 300000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
#  is_weighted: False
#  loss_type: l1
#  weight: 1.0
  is_weighted: True
  loss_type: ~
  weight: 1.0


  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
